FROM toendeavour/archlinux:base-i686

RUN sed -i -e 's/Architecture = auto/Architecture = i686/g' /etc/pacman.conf && \
    pacman -Sy && pacman -Sqg base | sort -u > /tmp/packages1 && \
    echo "linux" > /tmp/packages2 && \
    pacman --needed --noconfirm -Syu $(comm -23 /tmp/packages1 /tmp/packages2) && \
    sed -i -e 's/Architecture = i686/Architecture = auto/g' /etc/pacman.conf && \
    rm -Rf "/var/cache" && \
    rm -Rf "/var/lib/pacman/sync" && \
    rm -Rf "/var/log/*" && \
    install -m 0755 -d "/var/cache/pacman/pkg" 
