FROM alpine:latest

ENV ARCHITECTURE="aarch64"
ADD https://itmettke.de/.data/.linux/.archlinux-arm/${ARCHITECTURE}/${ARCHITECTURE}.tar.bzip2 /tmp

RUN mkdir /tmp/armChroot && \
    cd /tmp/armChroot && \
    tar --extract \
        --bzip2 \
        --file=../${ARCHITECTURE}.tar.bzip2 \
        .

##########

FROM scratch

COPY --from=0 /tmp/armChroot /

RUN [ "cross-build-start" ]
RUN pacman-key --init && \
    pacman-key --populate archlinux && \
    pacman-key --populate archlinuxarm && \
    sed -i -e 's/SigLevel = Never/#SigLevel = Never/g' /etc/pacman.conf && \
    sed -i -e 's/#SigLevel    = Required DatabaseOptional/SigLevel    = Required DatabaseOptional/g' /etc/pacman.conf && \
    sed -i -e 's/#LocalFileSigLevel = Optional/LocalFileSigLevel = Optional/g' /etc/pacman.conf && \
    pacman --needed --noconfirm -Syu base && \
    rm -Rf "/var/cache" && \
    rm -Rf "/var/lib/pacman/sync" && \
    rm -Rf "/var/log" && \
    install -m 0755 -d "/var/cache/pacman/pkg" 
RUN [ "cross-build-end" ]

##########

FROM scratch
LABEL maintainer="Marc Mettke <marc@itmettke.de>"

COPY --from=1 / /
