FROM alpine:latest

ENV ARCHITECTURE="armv7h"
ADD https://itmettke.de/.data/.linux/.archlinux-arm/${ARCHITECTURE}.tar.bzip2 /tmp

RUN mkdir /tmp/armChroot && \
    cd /tmp/armChroot && \
    tar --extract \
        --bzip2 \
        --file=../${ARCHITECTURE}.tar.bzip2 \
        .

##########

FROM scratch

COPY --from=0 /tmp/armChroot /

RUN [ "cross-build-start" ]
RUN pacman --noconfirm -Syu && \
    rm -Rf "/var/cache" && \
    rm -Rf "/var/lib/pacman/sync" && \
    rm -Rf "/var/log"
RUN [ "cross-build-end" ]

##########

FROM scratch
LABEL maintainer="Marc Mettke <marc@itmettke.de>"

COPY --from=1 / /
